#数据库连接池配置
spring:
    datasource:
        # 驱动配置
        # 连接池类型  spring boot 1.3版本  1.4.1版本支持
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://10.73.181.25:3306/generalbase?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        # 连接池配置
        # 初始化大小，最小，最大
        initialSize: 5
        maxActive: 20
        minIdle: 5
        # 配置获取连接等待超时的时间 单位毫秒
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#应用端口配置
server:
    port: 8085

#日志配置
logging:
    level:
      com.ibatis: INFO
      org.apache.http: INFO
    file: logs/springboot.log
